min_acl: private # also document private classes, Default would be "public"
clean: true
objc: true
#swift_version: 3.0
sdk: iphonesimulator
#sdk: iphone
umbrella_header: Header-ios-objc-foundation-nmxcore.h
framework_root: Development/NMXCore.xcodeproj
author: Namics AG
author_url: https://namics.com
module: NamicsLib
module_version: 1.0
copyright: "2016-present © Namics AG"
github_url: https://git.namics.com/namics/namics-core-library-ios-objective-c/
#xcodebuild_arguments: [clean,build,-project,NMXCore.xcodeproj,-target,NMXCore,-scheme,NMXCore]
